config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  get 'pages/show'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
  
  resources :kintais

end

app/models/kintai.rb
class Kintai < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
  
  has_many :kintais, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kintais_controller.rb
class KintaisController < ApplicationController
  def index
  end

  def new
    now_time = Time.current
    # 今日のはじまり
    from = now_time.beginning_of_day
    # 今日のおわり
    to = now_time.end_of_day
    @kintai = current_user.kintais.find_or_initialize_by(created_at: from..to)
  end

  def create
    if Kintai.create(user_id: current_user.id, started_at: Time.current)
      flash[:success] = '本日も頑張って行きましょう！'
      redirect_to new_kintai_path
    else
      render :new
    end
  end
  
  def update
    @kintai = Kintai.find(params[:id])
    if @kintai.update(finished_at: Time.current)
      flash[:success] = '本日もお疲れ様でした！'
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params.merge(name: params[:name]))
    @user.skip_confirmation!
    if @user.save
      flash[:success] = '登録完了しました。'
      redirect_to root_path
    else
      render :new
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kintais_helper.rb
module KintaisHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/kintais/index.html.erb
<h2>Section title</h2>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>勤務日</th>
        <th>出勤〜退勤</th>
      </tr>
    </thead>
    <tbody>
      <% @kintai.each do |kintai| %>
      <tr>
        <td><%= kintai.id %></td>
        <td><%= kintai.created_at.strftime("%Y/%m/%d") %></td>
        <td><%= kintai.started_at.strftime("%H:%M") %> ~ 
            <%= kintai.finished_at.strftime("%H:%M") %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/kintais/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
  <h1 class="h2">
    <%= fa_icon "clock-o", text: "勤怠" %>
  </h1>
</div>

<% if @kintai.finished_at %>
  本日もお疲れ様でした。
<% else %>
  <% if @kintai.new_record? %>
    <div class="jumbotron text-center">
      <h1 id="time" class="display-3"></h1>
      <hr class="my-4">
      <p class="lead">
        おはようございます！<br>
        本日も1日頑張って行きましょう！
      </p>
      <%= link_to fa_icon("sign-in 6x", text: '出勤'), kintais_path, method: :post, class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% else %>
    <div class="jumbotron text-center">
      <h1 id="time" class="display-3"></h1>
      <hr class="my-4">
      <%= link_to fa_icon("sign-out 6x", text: '退勤'), kintai_path(@kintai), method: :patch, class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">
<!--
function RealTimer() {
  var date = new Date();
  var time = date.toLocaleString();
  var hour = date.getHours();
  var min  = date.getMinutes();
  var sec  = date.getSeconds();
  if(hour < 10){ hour = "0" + hour; }
  if(min < 10) { min = "0" + min; }
  if(sec < 10) { sec = "0" + sec; }

  $("#time").text(time);
	setTimeout(RealTimer, 1000);
}
window.onload = RealTimer;
// -->
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>勤怠管理くん</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <% if user_signed_in? %>
       <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
          <a class="navbar-brand col-sm-3 col-md-10 mr-0" href="<% root_path %>">勤怠管理 ver.1.0</a>
          <%= link_to 'ホーム', root_path, class: 'text-white' %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'text-white' %>

          <ul class="navbar-nav px-3">
            <li class="nav-item">
              <a href="<%= edit_user_registration_path %>">
                <%= fa_icon "user-circle", class: 'nav-link' %>
              </a>
            </li>
          </ul>
        </nav>

        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>

        <div class="container-fluid">
          <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
              <div class="sidebar-sticky">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link active" href="<%= new_kintai_path %>">
                      <%= fa_icon "clock-o fw", text: "勤怠" %>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <%= fa_icon "question fw", text: "項目未定" %>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <%= fa_icon "question fw", text: "項目未定" %>
                    </a>
                  </li>
                </ul>
              </div>
            </nav>
    
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
              <%= yield %>
            </main>
          </div>
        </div>
    <% else %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= link_to 'サインアップ', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
        
        <%= yield %>
    <% end %>
</body>
</html>

app/views/pages/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>ホーム</title>


    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <p><%= image_tag '7320a.png' %></p>
    <form class="form-signin">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label>ようこそ</label>
  </body>
</html>

app/views/pages/show.html.erb
<h1>こんにちは、<%= current_user.username %>さん</h1>
<p>ユーザー用ページです。</p>